// Code generated by ogen, DO NOT EDIT.

package fincode

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

type CustomersPostBadRequest struct {
	Errors []CustomersPostBadRequestErrorsItem `json:"errors"`
}

// GetErrors returns the value of Errors.
func (s *CustomersPostBadRequest) GetErrors() []CustomersPostBadRequestErrorsItem {
	return s.Errors
}

// SetErrors sets the value of Errors.
func (s *CustomersPostBadRequest) SetErrors(val []CustomersPostBadRequestErrorsItem) {
	s.Errors = val
}

func (*CustomersPostBadRequest) customersPostRes() {}

type CustomersPostBadRequestErrorsItem struct {
	ErrorCode    OptString `json:"error_code"`
	ErrorMessage OptString `json:"error_message"`
}

// GetErrorCode returns the value of ErrorCode.
func (s *CustomersPostBadRequestErrorsItem) GetErrorCode() OptString {
	return s.ErrorCode
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *CustomersPostBadRequestErrorsItem) GetErrorMessage() OptString {
	return s.ErrorMessage
}

// SetErrorCode sets the value of ErrorCode.
func (s *CustomersPostBadRequestErrorsItem) SetErrorCode(val OptString) {
	s.ErrorCode = val
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *CustomersPostBadRequestErrorsItem) SetErrorMessage(val OptString) {
	s.ErrorMessage = val
}

type CustomersPostOK struct {
	ID                      OptString `json:"id"`
	Name                    OptString `json:"name"`
	Email                   OptString `json:"email"`
	PhoneCc                 OptString `json:"phone_cc"`
	PhoneNo                 OptString `json:"phone_no"`
	AddrCity                OptString `json:"addr_city"`
	AddrCountry             OptString `json:"addr_country"`
	AddrLine1               OptString `json:"addr_line_1"`
	AddrLine2               OptString `json:"addr_line_2"`
	AddrLine3               OptString `json:"addr_line_3"`
	AddrPostCode            OptString `json:"addr_post_code"`
	AddrState               OptString `json:"addr_state"`
	CardRegistration        OptString `json:"card_registration"`
	DerectdebitRegistration OptString `json:"derectdebit_registration"`
	Created                 OptString `json:"created"`
	Updated                 OptString `json:"updated"`
}

// GetID returns the value of ID.
func (s *CustomersPostOK) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *CustomersPostOK) GetName() OptString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *CustomersPostOK) GetEmail() OptString {
	return s.Email
}

// GetPhoneCc returns the value of PhoneCc.
func (s *CustomersPostOK) GetPhoneCc() OptString {
	return s.PhoneCc
}

// GetPhoneNo returns the value of PhoneNo.
func (s *CustomersPostOK) GetPhoneNo() OptString {
	return s.PhoneNo
}

// GetAddrCity returns the value of AddrCity.
func (s *CustomersPostOK) GetAddrCity() OptString {
	return s.AddrCity
}

// GetAddrCountry returns the value of AddrCountry.
func (s *CustomersPostOK) GetAddrCountry() OptString {
	return s.AddrCountry
}

// GetAddrLine1 returns the value of AddrLine1.
func (s *CustomersPostOK) GetAddrLine1() OptString {
	return s.AddrLine1
}

// GetAddrLine2 returns the value of AddrLine2.
func (s *CustomersPostOK) GetAddrLine2() OptString {
	return s.AddrLine2
}

// GetAddrLine3 returns the value of AddrLine3.
func (s *CustomersPostOK) GetAddrLine3() OptString {
	return s.AddrLine3
}

// GetAddrPostCode returns the value of AddrPostCode.
func (s *CustomersPostOK) GetAddrPostCode() OptString {
	return s.AddrPostCode
}

// GetAddrState returns the value of AddrState.
func (s *CustomersPostOK) GetAddrState() OptString {
	return s.AddrState
}

// GetCardRegistration returns the value of CardRegistration.
func (s *CustomersPostOK) GetCardRegistration() OptString {
	return s.CardRegistration
}

// GetDerectdebitRegistration returns the value of DerectdebitRegistration.
func (s *CustomersPostOK) GetDerectdebitRegistration() OptString {
	return s.DerectdebitRegistration
}

// GetCreated returns the value of Created.
func (s *CustomersPostOK) GetCreated() OptString {
	return s.Created
}

// GetUpdated returns the value of Updated.
func (s *CustomersPostOK) GetUpdated() OptString {
	return s.Updated
}

// SetID sets the value of ID.
func (s *CustomersPostOK) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *CustomersPostOK) SetName(val OptString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *CustomersPostOK) SetEmail(val OptString) {
	s.Email = val
}

// SetPhoneCc sets the value of PhoneCc.
func (s *CustomersPostOK) SetPhoneCc(val OptString) {
	s.PhoneCc = val
}

// SetPhoneNo sets the value of PhoneNo.
func (s *CustomersPostOK) SetPhoneNo(val OptString) {
	s.PhoneNo = val
}

// SetAddrCity sets the value of AddrCity.
func (s *CustomersPostOK) SetAddrCity(val OptString) {
	s.AddrCity = val
}

// SetAddrCountry sets the value of AddrCountry.
func (s *CustomersPostOK) SetAddrCountry(val OptString) {
	s.AddrCountry = val
}

// SetAddrLine1 sets the value of AddrLine1.
func (s *CustomersPostOK) SetAddrLine1(val OptString) {
	s.AddrLine1 = val
}

// SetAddrLine2 sets the value of AddrLine2.
func (s *CustomersPostOK) SetAddrLine2(val OptString) {
	s.AddrLine2 = val
}

// SetAddrLine3 sets the value of AddrLine3.
func (s *CustomersPostOK) SetAddrLine3(val OptString) {
	s.AddrLine3 = val
}

// SetAddrPostCode sets the value of AddrPostCode.
func (s *CustomersPostOK) SetAddrPostCode(val OptString) {
	s.AddrPostCode = val
}

// SetAddrState sets the value of AddrState.
func (s *CustomersPostOK) SetAddrState(val OptString) {
	s.AddrState = val
}

// SetCardRegistration sets the value of CardRegistration.
func (s *CustomersPostOK) SetCardRegistration(val OptString) {
	s.CardRegistration = val
}

// SetDerectdebitRegistration sets the value of DerectdebitRegistration.
func (s *CustomersPostOK) SetDerectdebitRegistration(val OptString) {
	s.DerectdebitRegistration = val
}

// SetCreated sets the value of Created.
func (s *CustomersPostOK) SetCreated(val OptString) {
	s.Created = val
}

// SetUpdated sets the value of Updated.
func (s *CustomersPostOK) SetUpdated(val OptString) {
	s.Updated = val
}

func (*CustomersPostOK) customersPostRes() {}

type CustomersPostReq struct {
	ID           OptString `json:"id"`
	Name         OptString `json:"name"`
	Email        OptString `json:"email"`
	PhoneCc      OptString `json:"phone_cc"`
	PhoneNo      OptString `json:"phone_no"`
	AddrCity     OptString `json:"addr_city"`
	AddrCountry  OptString `json:"addr_country"`
	AddrLine1    OptString `json:"addr_line_1"`
	AddrLine2    OptString `json:"addr_line_2"`
	AddrLine3    OptString `json:"addr_line_3"`
	AddrPostCode OptString `json:"addr_post_code"`
	AddrState    OptString `json:"addr_state"`
}

// GetID returns the value of ID.
func (s *CustomersPostReq) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *CustomersPostReq) GetName() OptString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *CustomersPostReq) GetEmail() OptString {
	return s.Email
}

// GetPhoneCc returns the value of PhoneCc.
func (s *CustomersPostReq) GetPhoneCc() OptString {
	return s.PhoneCc
}

// GetPhoneNo returns the value of PhoneNo.
func (s *CustomersPostReq) GetPhoneNo() OptString {
	return s.PhoneNo
}

// GetAddrCity returns the value of AddrCity.
func (s *CustomersPostReq) GetAddrCity() OptString {
	return s.AddrCity
}

// GetAddrCountry returns the value of AddrCountry.
func (s *CustomersPostReq) GetAddrCountry() OptString {
	return s.AddrCountry
}

// GetAddrLine1 returns the value of AddrLine1.
func (s *CustomersPostReq) GetAddrLine1() OptString {
	return s.AddrLine1
}

// GetAddrLine2 returns the value of AddrLine2.
func (s *CustomersPostReq) GetAddrLine2() OptString {
	return s.AddrLine2
}

// GetAddrLine3 returns the value of AddrLine3.
func (s *CustomersPostReq) GetAddrLine3() OptString {
	return s.AddrLine3
}

// GetAddrPostCode returns the value of AddrPostCode.
func (s *CustomersPostReq) GetAddrPostCode() OptString {
	return s.AddrPostCode
}

// GetAddrState returns the value of AddrState.
func (s *CustomersPostReq) GetAddrState() OptString {
	return s.AddrState
}

// SetID sets the value of ID.
func (s *CustomersPostReq) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *CustomersPostReq) SetName(val OptString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *CustomersPostReq) SetEmail(val OptString) {
	s.Email = val
}

// SetPhoneCc sets the value of PhoneCc.
func (s *CustomersPostReq) SetPhoneCc(val OptString) {
	s.PhoneCc = val
}

// SetPhoneNo sets the value of PhoneNo.
func (s *CustomersPostReq) SetPhoneNo(val OptString) {
	s.PhoneNo = val
}

// SetAddrCity sets the value of AddrCity.
func (s *CustomersPostReq) SetAddrCity(val OptString) {
	s.AddrCity = val
}

// SetAddrCountry sets the value of AddrCountry.
func (s *CustomersPostReq) SetAddrCountry(val OptString) {
	s.AddrCountry = val
}

// SetAddrLine1 sets the value of AddrLine1.
func (s *CustomersPostReq) SetAddrLine1(val OptString) {
	s.AddrLine1 = val
}

// SetAddrLine2 sets the value of AddrLine2.
func (s *CustomersPostReq) SetAddrLine2(val OptString) {
	s.AddrLine2 = val
}

// SetAddrLine3 sets the value of AddrLine3.
func (s *CustomersPostReq) SetAddrLine3(val OptString) {
	s.AddrLine3 = val
}

// SetAddrPostCode sets the value of AddrPostCode.
func (s *CustomersPostReq) SetAddrPostCode(val OptString) {
	s.AddrPostCode = val
}

// SetAddrState sets the value of AddrState.
func (s *CustomersPostReq) SetAddrState(val OptString) {
	s.AddrState = val
}

// NewOptCustomersPostReq returns new OptCustomersPostReq with value set to v.
func NewOptCustomersPostReq(v CustomersPostReq) OptCustomersPostReq {
	return OptCustomersPostReq{
		Value: v,
		Set:   true,
	}
}

// OptCustomersPostReq is optional CustomersPostReq.
type OptCustomersPostReq struct {
	Value CustomersPostReq
	Set   bool
}

// IsSet returns true if OptCustomersPostReq was set.
func (o OptCustomersPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCustomersPostReq) Reset() {
	var v CustomersPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCustomersPostReq) SetTo(v CustomersPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCustomersPostReq) Get() (v CustomersPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCustomersPostReq) Or(d CustomersPostReq) CustomersPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
