// Code generated by ogen, DO NOT EDIT.
package api

type CustomersIDDeleteRes interface {
	customersIDDeleteRes()
}

type CustomersIDGetRes interface {
	customersIDGetRes()
}

type CustomersPostRes interface {
	customersPostRes()
}
