// Code generated by ogen, DO NOT EDIT.
package api

type AuthorizePaymentRes interface {
	authorizePaymentRes()
}

type CancelPaymentRes interface {
	cancelPaymentRes()
}

type CapturePaymentRes interface {
	capturePaymentRes()
}

type ChangeAmountOfPaymentRes interface {
	changeAmountOfPaymentRes()
}

type Confirm3DSecureAuthenticationRes interface {
	confirm3DSecureAuthenticationRes()
}

type CreateCardRegistrationSessionRes interface {
	createCardRegistrationSessionRes()
}

type CreateCustomerCardRes interface {
	createCustomerCardRes()
}

type CreateCustomerPaymentMethodRes interface {
	createCustomerPaymentMethodRes()
}

type CreateCustomerRes interface {
	createCustomerRes()
}

type CreatePaymentBulkRes interface {
	createPaymentBulkRes()
}

type CreatePaymentRes interface {
	createPaymentRes()
}

type CreatePaymentSessionRes interface {
	createPaymentSessionRes()
}

type CreatePlanRes interface {
	createPlanRes()
}

type CreateSubscriptionRes interface {
	createSubscriptionRes()
}

type CreateTenantWithExistingUserRes interface {
	createTenantWithExistingUserRes()
}

type CreateTenantWithNewUserRes interface {
	createTenantWithNewUserRes()
}

type CreateWebhookSettingRes interface {
	createWebhookSettingRes()
}

type DeleteCustomerCardRes interface {
	deleteCustomerCardRes()
}

type DeleteCustomerPaymentMethodRes interface {
	deleteCustomerPaymentMethodRes()
}

type DeleteCustomerRes interface {
	deleteCustomerRes()
}

type DeletePaymentBulkRes interface {
	deletePaymentBulkRes()
}

type DeletePlanRes interface {
	deletePlanRes()
}

type DeleteSubscriptionRes interface {
	deleteSubscriptionRes()
}

type DeleteWebhookSettingRes interface {
	deleteWebhookSettingRes()
}

type Execute3DSecureAuthenticationRes interface {
	execute3DSecureAuthenticationRes()
}

type ExecutePaymentAfter3DSecureRes interface {
	executePaymentAfter3DSecureRes()
}

type ExecutePaymentRes interface {
	executePaymentRes()
}

type GenerateBarcodeOfPaymentRes interface {
	generateBarcodeOfPaymentRes()
}

type ReceiveWebhookOfApplePayPaymentRes interface {
	receiveWebhookOfApplePayPaymentRes()
}

type ReceiveWebhookOfCardPaymentBulkBatchRes interface {
	receiveWebhookOfCardPaymentBulkBatchRes()
}

type ReceiveWebhookOfCardPaymentRes interface {
	receiveWebhookOfCardPaymentRes()
}

type ReceiveWebhookOfCardRecurringBatchRes interface {
	receiveWebhookOfCardRecurringBatchRes()
}

type ReceiveWebhookOfCardRes interface {
	receiveWebhookOfCardRes()
}

type ReceiveWebhookOfCardSubscriptionRes interface {
	receiveWebhookOfCardSubscriptionRes()
}

type ReceiveWebhookOfContractRes interface {
	receiveWebhookOfContractRes()
}

type ReceiveWebhookOfCustomerPaymentMethodRes interface {
	receiveWebhookOfCustomerPaymentMethodRes()
}

type ReceiveWebhookOfDirectDebitPaymentRes interface {
	receiveWebhookOfDirectDebitPaymentRes()
}

type ReceiveWebhookOfDirectDebitRecurringBatchRes interface {
	receiveWebhookOfDirectDebitRecurringBatchRes()
}

type ReceiveWebhookOfDirectDebitSubscriptionRes interface {
	receiveWebhookOfDirectDebitSubscriptionRes()
}

type ReceiveWebhookOfKonbiniPaymentRes interface {
	receiveWebhookOfKonbiniPaymentRes()
}

type ReceiveWebhookOfPayPayPaymentRes interface {
	receiveWebhookOfPayPayPaymentRes()
}

type ReceiveWebhookOfRegisteringCardPaymentBulkRes interface {
	receiveWebhookOfRegisteringCardPaymentBulkRes()
}

type RequestProductionEnvironmentRes interface {
	requestProductionEnvironmentRes()
}

type ReserveProviderRes interface {
	reserveProviderRes()
}

type RetrieveAccountDetailListRes interface {
	retrieveAccountDetailListRes()
}

type RetrieveAccountListRes interface {
	retrieveAccountListRes()
}

type RetrieveAccountRes interface {
	retrieveAccountRes()
}

type RetrieveCustomerCardListRes interface {
	retrieveCustomerCardListRes()
}

type RetrieveCustomerCardRes interface {
	retrieveCustomerCardRes()
}

type RetrieveCustomerListRes interface {
	retrieveCustomerListRes()
}

type RetrieveCustomerPaymentMethodListRes interface {
	retrieveCustomerPaymentMethodListRes()
}

type RetrieveCustomerPaymentMethodRes interface {
	retrieveCustomerPaymentMethodRes()
}

type RetrieveCustomerRes interface {
	retrieveCustomerRes()
}

type RetrievePaymentBulkDetailListRes interface {
	retrievePaymentBulkDetailListRes()
}

type RetrievePaymentBulkListRes interface {
	retrievePaymentBulkListRes()
}

type RetrievePaymentListRes interface {
	retrievePaymentListRes()
}

type RetrievePaymentRes interface {
	retrievePaymentRes()
}

type RetrievePlanListRes interface {
	retrievePlanListRes()
}

type RetrievePlanRes interface {
	retrievePlanRes()
}

type RetrievePlatformAccountListRes interface {
	retrievePlatformAccountListRes()
}

type RetrievePlatformAccountRes interface {
	retrievePlatformAccountRes()
}

type RetrievePlatformAccountSummaryListRes interface {
	retrievePlatformAccountSummaryListRes()
}

type RetrievePlatformShopListRes interface {
	retrievePlatformShopListRes()
}

type RetrievePlatformShopRes interface {
	retrievePlatformShopRes()
}

type RetrieveSubscriptionListRes interface {
	retrieveSubscriptionListRes()
}

type RetrieveSubscriptionRes interface {
	retrieveSubscriptionRes()
}

type RetrieveSubscriptionResultListRes interface {
	retrieveSubscriptionResultListRes()
}

type RetrieveTenantContractRes interface {
	retrieveTenantContractRes()
}

type RetrieveTenantExaminationInfoRes interface {
	retrieveTenantExaminationInfoRes()
}

type RetrieveTenantExaminationInfoV2Res interface {
	retrieveTenantExaminationInfoV2Res()
}

type RetrieveTenantShopListRes interface {
	retrieveTenantShopListRes()
}

type RetrieveTenantShopRes interface {
	retrieveTenantShopRes()
}

type RetrieveWebhookSettingListRes interface {
	retrieveWebhookSettingListRes()
}

type RetrieveWebhookSettingRes interface {
	retrieveWebhookSettingRes()
}

type UpdateCustomerCardRes interface {
	updateCustomerCardRes()
}

type UpdateCustomerRes interface {
	updateCustomerRes()
}

type UpdatePlanRes interface {
	updatePlanRes()
}

type UpdatePlatformShopRes interface {
	updatePlatformShopRes()
}

type UpdateSubscriptionRes interface {
	updateSubscriptionRes()
}

type UpdateTenantExaminationInfoRes interface {
	updateTenantExaminationInfoRes()
}

type UpdateTenantExaminationInfoV2Res interface {
	updateTenantExaminationInfoV2Res()
}

type UpdateTenantShopRes interface {
	updateTenantShopRes()
}

type UpdateWebhookSettingRes interface {
	updateWebhookSettingRes()
}

type UploadExaminationFileRes interface {
	uploadExaminationFileRes()
}
