// Code generated by ogen, DO NOT EDIT.
package api

type CustomersCustomerIDCardsIDDeleteRes interface {
	customersCustomerIDCardsIDDeleteRes()
}

type CustomersCustomerIDCardsIDGetRes interface {
	customersCustomerIDCardsIDGetRes()
}

type CustomersCustomerIDPaymentMethodsPaymentMethodIDDeleteRes interface {
	customersCustomerIDPaymentMethodsPaymentMethodIDDeleteRes()
}

type CustomersCustomerIDPaymentMethodsPaymentMethodIDGetRes interface {
	customersCustomerIDPaymentMethodsPaymentMethodIDGetRes()
}

type CustomersCustomerIDPaymentMethodsPostRes interface {
	customersCustomerIDPaymentMethodsPostRes()
}

type CustomersIDDeleteRes interface {
	customersIDDeleteRes()
}

type CustomersIDGetRes interface {
	customersIDGetRes()
}

type CustomersPostRes interface {
	customersPostRes()
}

type PaymentsGetRes interface {
	paymentsGetRes()
}

type PaymentsIDAuthPutRes interface {
	paymentsIDAuthPutRes()
}

type PaymentsIDCancelPutRes interface {
	paymentsIDCancelPutRes()
}

type PaymentsIDGetRes interface {
	paymentsIDGetRes()
}

type PaymentsIDPutRes interface {
	paymentsIDPutRes()
}

type PaymentsPostRes interface {
	paymentsPostRes()
}
