// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CustomersCustomerIDCardsIDDeleteOperation                       OperationName = "CustomersCustomerIDCardsIDDelete"
	CustomersCustomerIDCardsIDGetOperation                          OperationName = "CustomersCustomerIDCardsIDGet"
	CustomersCustomerIDPaymentMethodsPaymentMethodIDDeleteOperation OperationName = "CustomersCustomerIDPaymentMethodsPaymentMethodIDDelete"
	CustomersCustomerIDPaymentMethodsPaymentMethodIDGetOperation    OperationName = "CustomersCustomerIDPaymentMethodsPaymentMethodIDGet"
	CustomersCustomerIDPaymentMethodsPostOperation                  OperationName = "CustomersCustomerIDPaymentMethodsPost"
	CustomersIDDeleteOperation                                      OperationName = "CustomersIDDelete"
	CustomersIDGetOperation                                         OperationName = "CustomersIDGet"
	CustomersPostOperation                                          OperationName = "CustomersPost"
	PaymentsGetOperation                                            OperationName = "PaymentsGet"
	PaymentsIDAuthPutOperation                                      OperationName = "PaymentsIDAuthPut"
	PaymentsIDCancelPutOperation                                    OperationName = "PaymentsIDCancelPut"
	PaymentsIDCapturePutOperation                                   OperationName = "PaymentsIDCapturePut"
	PaymentsIDGetOperation                                          OperationName = "PaymentsIDGet"
	PaymentsIDPutOperation                                          OperationName = "PaymentsIDPut"
	PaymentsPostOperation                                           OperationName = "PaymentsPost"
)
