// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreatePaymentOK2) setDefaults() {
	{
		val := string("2")
		s.PaymentTermDay.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ExecutePaymentOK2) setDefaults() {
	{
		val := string("2")
		s.PaymentTermDay.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GenerateBarcodeOfPaymentOK) setDefaults() {
	{
		val := string("2")
		s.PaymentTermDay.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PaymentSessionCreatingRequestTransaction) setDefaults() {
	{
		s.Tax.Null = true
	}
}

// setDefaults set default value of fields.
func (s *PaymentSessionCreatingResponseCard) setDefaults() {
	{
		val := CardPaymentSessionJobCode("AUTH")
		s.JobCode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RetrievePaymentOK2) setDefaults() {
	{
		val := string("2")
		s.PaymentTermDay.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RetrievePlatformShopListQuery) setDefaults() {
	{
		s.ID.Null = true
	}
	{
		s.ShopName.Null = true
	}
	{
		s.ShopMailAddress.Null = true
	}
	{
		s.CreatedFrom.Null = true
	}
	{
		s.CreatedTo.Null = true
	}
}

// setDefaults set default value of fields.
func (s *RetrieveTenantShopListQuery) setDefaults() {
	{
		s.ID.Null = true
	}
	{
		s.ShopName.Null = true
	}
	{
		s.ShopMailAddress.Null = true
	}
	{
		s.CreatedFrom.Null = true
	}
	{
		s.CreatedTo.Null = true
	}
}
